### ISSUE TITLE
speciesIdx argument

### ISSUE THREAD

**Issue by Scott-Foster** [skiptoniam/qrbp#11]
Hi Skip,

Just trying to progress/resurrect some of my code that uses ppmData...  Finally got some time.

Having issues with ppmData through. Specifically, the speciesIdx argument.  It appears that you allow for values other than "SpeciesID", but then fail to pass them to getSppNames().  This means that the species list is empty -- not the desired outcome.

For now, I have made a work around.  You may want to fix though -- shouldn't take much.  If it annoys me further, then I will also fix.

Thanks again for putting this one together.

Scott

**Comment by skiptoniam** [comment]
I think this is fixed
