### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by mhesselbarth** [skiptoniam/qrbp#17]
Regarding https://github.com/openjournals/joss-reviews/issues/4771

Please provide an [OSI approved](https://opensource.org/licenses/alphabetical) software license. In the `DESCRIPTION` it says `License: MIT + file LICENSE`, thus I would suggest to actually include a text file with the MIT license.

**Comment by skiptoniam** [comment]
I think I have fixed this. I added in a MIT "LICENSE.md" file
