### ISSUE TITLE
Merge with ppmFit

### ISSUE THREAD

**Issue by mhesselbarth** [skiptoniam/qrbp#18]
Regarding https://github.com/openjournals/joss-reviews/issues/4771

Maybe it makes sense to merge the `ppmData` and `ppmFit` package into one package. I think the merged package would not be too big to successfully maintain and the functionality seems to be extremely related. 

However, I also understand that there might be reasons to keep the packages separated. Thus, this suggestion could also be ignored by the authors with some reasoning.

**Comment by skiptoniam** [comment]
At the moment, ppmFit is a fair way off being ready. And there are some methods still being worked up for this package - which might end up in other manuscripts. I do think this is a good idea in the long run. But I won't address if for this review https://github.com/openjournals/joss-reviews/issues/4771. I will close this issue for now.
