### ISSUE TITLE
testthat

### ISSUE THREAD

**Issue by mhesselbarth** [skiptoniam/qrbp#21]
Regarding https://github.com/openjournals/joss-reviews/issues/4771

It is appreciated and good practice that the package uses automated tests. However, currently none of the tests actually check if the function return values are correct using `testthat::expect_*()`. Thus, when running `evtools::test()` many of the tests are actually skipped because they are empty.

**Comment by skiptoniam** [comment]
I have updated the tests - I normally just check for code coverage, but this is a much better way of doing things. Thanks for the heads up.
