### ISSUE TITLE
Methods to convert from and to spatstat

### ISSUE THREAD

**Issue by mhesselbarth** [skiptoniam/qrbp#24]
Regarding https://github.com/openjournals/joss-reviews/issues/4771

Given the large amount of functions related to point pattern by the `spatstat` library and its popularity, it might make sense to also provide convert-function for `spatstat` objects (e.g., `ppp`, `owin`, etc.)

**Comment by skiptoniam** [comment]
added as.spatstat, as.ppp and as.owin for some spatstat integration.

**Comment by mhesselbarth** [comment]
Cool, looking good to me. For the future, would be easier if you tag the commits in the issue. Alternatively you can include "fix #<issue>" in your commit and automatically close the issue by that.

https://github.com/skiptoniam/ppmData/commit/5683f1607e22f179712f001b7f93e88deab9a2d4

**Comment by skiptoniam** [comment]
Sweet. Thanks for the "fix #" tip, I wasn't aware of that one. I'll close this issue now.

**Comment by mhesselbarth** [comment]
Oh, I think must be "Fix"

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
