### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by mhesselbarth** [skiptoniam/qrbp#25]
Regarding https://github.com/openjournals/joss-reviews/issues/4771

According to the JOSS criteria, each package needs community guidelines on how to contribute [(see here)](https://joss.readthedocs.io/en/latest/review_criteria.html). Please provide these information using e.g. a Code of Conduct file.

**Comment by skiptoniam** [comment]
Thanks for this. Added a code of contact file and description in the readme
